### ISSUE TITLE
How to clean the cache

### ISSUE THREAD

**Issue by Mic92** [kalbasit/ncps#21]
Does this service also support cleaning caches? I only see code that adds more content.

**Comment by kalbasit** [comment]
Great point @Mic92, it's actually on the roadmap (I have not posted the roadmap). I'm thinking of adding a boltdb-like file to the cache to keep track of when cache paths were last pushed and last used to allow for garbage collection; The garbage collector will run on another port so I can use it from a Kubernetes CronJob without having to make it visible to the outside. What do you think about doing it this way?

**Comment by Mic92** [comment]
Sounds good, would the port access the same boltdb? You probably also can just do a simple LRU cache since for a passthru cache references don't matter as much.

**Comment by kalbasit** [comment]
@Mic92 the boltdb idea is to implement LRU, in a way. Of course,  I could make it automatically remove whatever falls outside the allowed size or do it via GC.

For now, I added `DELETE` routes, albeit un-authenticated.

**Comment by kalbasit** [comment]
@Mic92 this is now implemented, do you mind checking? I ended up going with a simple cron-based implementation instead of another server to listen to I figured not everyone runs k8s and this would be a lot simpler to adopt than to have to run a cron in another way.

**Comment by Mic92** [comment]
Nice. Maybe you want an index on `hash` eventually as it's used in every `touchNarInfoQuery`/`touchNarQuery`. @brianmcgee also recently showed me sqlc, [example](https://github.com/Mic92/niks3/blob/main/pg/query.sql), which saves quite a bit of boilercode to write. LRU caching on nar/narinfo for a passthru cache is fine, but might be a bit rough, if you actually plan to write to a binary cache yourself, as it will not take any dependencies into account. In [niks3](https://github.com/Mic92/niks3), we have the concept of [closures](https://github.com/Mic92/niks3/blob/c8b20021394bf2fa273d9f90e8f8242af59962a4/pg/migrations/20241026095416_initial_model.sql#L23). In our case a closure will be the high-level store path that is pushed to a binary cache, the closure will contain the store path itself and all its dependence. Multiple closures can refer to the same objects. But I am also fine testing it as a pure pull through cache. My hope is that we have a solution that we can provide to providers so that cache.nixos.org can save some traffic.

**Comment by Mic92** [comment]
One more question. Do you parallelize querying upstream caches?

**Comment by kalbasit** [comment]
> Nice. Maybe you want an index on `hash` eventually as it's used in every `touchNarInfoQuery`/`touchNarQuery`. @brianmcgee also recently showed me sqlc, [example](https://github.com/Mic92/niks3/blob/main/pg/query.sql?rgh-link-date=2024-12-09T07%3A11%3A34Z), which saves quite a bit of boilercode to write. LRU caching on nar/narinfo for a passthru cache is fine, but might be a bit rough, if you actually plan to write to a binary cache yourself, as it will not take any dependencies into account. In [niks3](https://github.com/Mic92/niks3), we have the concept of [closures](https://github.com/Mic92/niks3/blob/c8b20021394bf2fa273d9f90e8f8242af59962a4/pg/migrations/20241026095416_initial_model.sql#L23). In our case a closure will be the high-level store path that is pushed to a binary cache, the closure will contain the store path itself and all its dependence. Multiple closures can refer to the same objects. But I am also fine testing it as a pure pull through cache. My hope is that we have a solution that we can provide to providers so that cache.nixos.org can save some traffic.

The implementation is MVP as you can tell by the lack of indexes. I wanted to solve the smallest problem I can solve today, thinking of the cache as a closure is a bigger problem; And I'm not sure if the pass-thru cache is the right place to untangle it. For the time-being, I think cleaning nar/narinfo by simply looking at when was it the last time a nar was pulled is a much easier problem.



> One more question. Do you parallelize querying upstream caches?

For one nar/narinfo I do not, since ncps tries to honor the priority flag, it tries to pull from upstream caches one at a time until it's found; Also I didn't want to eat traffic from upstream caches that I won't be using. With that said, however, since an HTTP handler responds to http requests in go-routine then yes multiple nar/narinfo are pulled in parallel; Currently, I have not place a limit on how many download threads I have but it's possible to implement that using a limited set of workers working off of a channel.

p.s: I enabled [discussions](https://github.com/kalbasit/ncps/discussions) a better place for this sort of discussions than an unrelated issue 😄
